qt5-creator: upgrade to 4.5.1
Source: meta-qt5
MR: 00000
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: bc20e3dcd0176529740beb59ccf1f170b9f828a8
Description:

* old 3.5.1 isn't compatible with Qt 5.11
  qt-creator-opensource-src-3.5.1/src/libs/qmleditorwidgets/contextpanewidgetimage.cpp:891:23:
  error: invalid use of incomplete type 'class QStyle'
  |      QIcon icon(style()->standardIcon(QStyle::SP_DockWidgetCloseButton));
  |                        ^~

Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>