qtmultimedia: Pass -DMESA_EGL_NO_X11_HEADERS=1 when x is disabled
Source: meta-qt5
MR: 00000
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: 41666ddba78ff1f094310589489e0a070e0094d8
Description:

Some graphics drives e.g. mali/mesa depend on this define
to use proper guards in eglplatform.h

Fixes

| In file included from /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/qtmultimedia/5.10.1+gitAUTOINC+038716bb1f-r0/recipe-sysroot/usr/include/EGL/egl.h:36:0,
|                  from .moc/../../../../../../git/src/plugins/videonode/egl/qsgvideonode_egl.h:48,
|                  from .moc/moc_qsgvideonode_egl.cpp:9:
| /mnt/a/zonit/build/tmp/work/aarch64-bec-linux/qtmultimedia/5.10.1+gitAUTOINC+038716bb1f-r0/recipe-sysroot/usr/include/EGL/eglplatform.h:125:10: fatal error: X11/Xlib.h: No such file or directory
|  #include <X11/Xlib.h>
|           ^~~~~~~~~~~~
| compilation terminated.
| make[4]: *** [Makefile:461: .obj/moc_qsgvideonode_egl.o] Error 1

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>